DROP TABLE `INTERROGER` ;
DROP TABLE `REPONDRE` ;
DROP TABLE `CONSTITUER` ;

DROP TABLE `SONDE` ;
DROP TABLE `CARACTERISTIQUE` ;
DROP TABLE `VALPOSSIBLE` ;
DROP TABLE `QUESTION` ;
DROP TABLE `TYPEQUESTION` ;
DROP TABLE `QUESTIONNAIRE` ;
DROP TABLE `PANEL` ;
DROP TABLE `CLIENT` ;
DROP TABLE `CATEGORIE` ;
DROP TABLE `TRANCHE` ;
DROP TABLE `UTILISATEUR` ;
DROP TABLE `ROLEUTIL` ;
